#!/bin/bash
#
# AAI 0.1b - Here you go!
# 
#   Criado em 07/10/2017
# Alterado em 08/10/2017
# 
# Por: Arch Linux Brasil Dev Team

#############################################
########## Parametros básicos ###############
#############################################
if [ $(id -u) == 0 ]; then
   echo "Este script precisa ser usado como root." 1>&2
   exit 1
fi

apps=( "dialog" )

for app in ${apps[@]} 
do
    which $app 1> /dev/null 2> /dev/null
    if [ $? != 0 ]; then
        echo
        read -p "O aplicativo $app não foi encontrado. Deseja instalar? [s/N] " resp
        if [ $resp == [sS] ]; then 
            pacman -S $app
        else
        	echo "Programa abortado..."
        	exit 1
        fi
    fi
done

TEMAS=$(ls -1 temas/ | xargs -I{} basename {} .cfg | awk '{print $1, $1 ".cfg"}')
TEMA=$(dialog --backtitle "$titulo" --title "$subtitulo" --menu "Escolha o tema do AAI" 0 0 2 $TEMAS 3>&1 1>&2 2>&3)

if [ $? == 1 ]; then 
    TEMA="anywhere"
fi

#############################################
########## Parametros internos ##############
#############################################
titulo="Arch Linux Automatic Installer"
subtitulo="Arch Linux Automatic Installer"

#############################################
########### VARS ############################
#############################################
export DIALOGRC="temas/${TEMA}.cfg"

# Welcome
dialog --backtitle "$titulo" --title "$subtitulo" --textbox aai.txt 0 0 --and-widget --yesno "\nContinuar a instalação do Arch Linux?" 0 0 3>&1 1>&2 2>&3

if [ $? == 1 ]; then 
    exit
fi

#############################################
########### LOCALES #########################
#############################################
LOCALE=$(dialog --backtitle "$titulo" --title "$subtitulo" --inputbox "Seu locale atual:" 0 0 "br abnt2" 3>&1 1>&2 2>&3)
#localectl set-x11-keymap "$LOCALE"

# Conectividade
INTERFACES=$(ip -o link show | awk -F': ' '{print $2}' | egrep -v lo | awk '{print v++,$1}')
INTERFACE=$(dialog --backtitle "$titulo" --title "$subtitulo" --menu "Qual sua interface?" 0 0 3 $INTERFACES 3>&1 1>&2 2>&3)

# https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
# e = cabeada, w = wireless | systemd owns the world...
TIPO=$(echo $INTERFACE | head -c 1)

#dhcpcd $INTERFACE

#############################################
############ PARTICIONAMENTO ################
#############################################
DISCOS=$(basename -a $(ls -1 /dev/sd*) | tr -d [0-9] | uniq | awk '{print v++,$1}')
DISCO=$(dialog --backtitle "$titulo" --title "$subtitulo" --menu "Qual seu disco?" 0 0 4 $DISCOS 3>&1 1>&2 2>&3)


FILESYSTEMS=$(ls -1 /usr/bin/mkfs.* | awk -F'.' '{print $2}' | egrep -vi 'bfs|cramfs|ext2|fat|minix|msdos|udf|ufs' | awk '{print v++,$1}')
FILESYSTEM=$(dialog --backtitle "$titulo" --title "$subtitulo" --menu "Sistema de arquivos? (recomendamos ext4)" 0 0 5 $FILESYSTEMS 3>&1 1>&2 2>&3)


# WIP...
#$(cat $ARQUIVO | cut -d: -f1 | sed 's/$/ o/')
#sed -i '/TotalDownload/s/^#//g' /etc/pacman.conf
#pacman -S wpa_supplicant wpa_actiond dialog iw sudo bash-completion efibootmgr

exit 0